### ISSUE TITLE
MsgTx.BtcDecode can't decode transaction returned from https://github.com/litecoin-project/litecoin v0.21.2

### ISSUE THREAD

**Issue by zhenyuzhao-cb** [ltcsuite/ltcd#16]
github.com/litecoin-project/litecoin start encode mweb tx into hex from version v0.21.2. Current MsgTx.BtcDecode can't recognize the new flag, 0x08. To make it work with the new C++ server, let's skip the mweb tx section for now.

- Encoder in C++: https://github.com/litecoin-project/litecoin/blob/v0.21.2/src/primitives/transaction.h#L365-L367
- PR for a quick fix: https://github.com/ltcsuite/ltcd/pull/15

**Comment by losh11** [comment]
Fixed with #15
