### ISSUE TITLE
remove go.mod replace directives from tagged releases

### ISSUE THREAD

**Issue by chappjc** [ltcsuite/ltcd#21]
Go disallows using `go install` for revisions that have replace statements.  ltcd's tags all have replaces, so we get this:

```go
$  go install -v github.com/ltcsuite/ltcd@v0.22.0-beta
go: github.com/ltcsuite/ltcd@v0.22.0-beta (in github.com/ltcsuite/ltcd@v0.22.0-beta):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

When you plan to make a release, just point the `require` statements to tagged modules, **remove the `replaces`**, and `go mod tidy`.

When you re-enter a development cycle, you can add the `replace` statements back.

**Comment by losh11** [comment]
The issue is we're trying to follow upstream (btcsuite), and we aim to match the same versioning etc. This unfortunately requires the `replaces`, made worse by the circular deps. Unlikely to fix.
