### ISSUE TITLE
Error: script witness item is larger than the max allowed size [count 57628, max 11000]

### ISSUE THREAD

**Issue by zhenyuzhao-cb** [ltcsuite/ltcd#24]
To fix this error, we need to apply those fixes:
- https://github.com/btcsuite/btcd/pull/1896 
- https://github.com/btcsuite/btcd/pull/1907

**Comment by losh11** [comment]
Thanks! I'm likely going to be syncing with upstream soon, so this should be included.

**Comment by zhenyuzhao-cb** [comment]
Hi losh11, 

I prepared a cherry pick PR for this issue: https://github.com/ltcsuite/ltcd/pull/25

Thanks,
Zhenyu

**Comment by parihaaraka** [comment]
Block reading stuck for 2 days... There will probably be one more fork :/

**Comment by Sergantkamo** [comment]
Господа, когда запустится ltc?

**Comment by idrisovislam98** [comment]
hello when will the bug be fixed?

**Comment by losh11** [comment]
Issue has been fixed.
