### ISSUE TITLE
Transaction ID "No matching records found" on a confirmed transaction

### ISSUE THREAD

**Issue by jjttjeff** [ltcsuite/ltcd#26]
sent 1.3917721 LTC to address ltc1qk80pky0f9uuf7ctdlf2frc0ws0yes03d39sv0r (a waves platform exchange address)
The LTC is not available and the support team at waves pointed me to this github.  The transaction ID is e4941e8ad5b80daba998d8f9515b0fb6e8afc78a972316417c966cf049248dcb which is showing me this in the LTC block explorer

**Comment by idrisovislam98** [comment]
> отправил 1.3917721 LTC на адрес ltc1qk80pky0f9uuf7ctdlf2frc0ws0yes03d39sv0r (адрес обмена платформы Waves). LTC недоступен, и служба поддержки Waves указала мне на этот github. Идентификатор транзакции - e4941e8ad5b80daba998d8f9515b0fb6e8afc78a972316417c966cf049248dcb, который показывает мне это в обозревателе блоков LTC.

Ну и что тебе ответили или помогли как то?
