### ISSUE TITLE
segmentation violation

### ISSUE THREAD

**Issue by parihaaraka** [ltcsuite/ltcd#27]
[httpResponse may be nil](https://github.com/ltcsuite/ltcd/blob/d6898fbac50050ebe0771b3ce5d78243d0c1b8de/rpcclient/infrastructure.go#L814)

**Comment by parihaaraka** [comment]
[fixed in btcd](https://github.com/btcsuite/btcd/blob/a18c2cfbf8929b7950da34b09c1dec27646a61d6/rpcclient/infrastructure.go#L839)

**Comment by losh11** [comment]
Fixed with ad811a93fe09c708aec5f5453050a45777a73b0e
