### ISSUE TITLE
unsupported witness version: 0x8

### ISSUE THREAD

**Issue by parihaaraka** [ltcsuite/ltcd#30]
`can't decode address ltc1gh72nxpuljst25q0yu07rxzcquuh5v762pgdv9t6yk6q879rcf39scgu2am: unsupported witness version: 0x8`
something changed again?

**Comment by parihaaraka** [comment]
looks like my bad while fixing taproot

**Comment by parihaaraka** [comment]
[picolloo](https://github.com/ltcsuite/ltcd/pull/22) fix has the same problem

**Comment by losh11** [comment]
@picolloo's PR won't be merged. All their tests haven't been ported over correctly. When I was working on syncing with upstream at the time taproot code wasn't merged. Will see if I can add in taproot support before syncing with newer changes.

**Comment by pikonha** [comment]
I'll try to use LTC addresses on the tests so we can proceed with this MR

**Comment by losh11** [comment]
ltcd v0.23.3 is currently a WIP and should be ready and tagged within the end of the week (currently reviewing and fixing tests) - taproot is now fully supported! closing :)
